# Generated by Django 5.2.7 on 2025-11-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='done',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
