# Generated by Django 5.2.7 on 2025-11-03 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todoitem_done_todoitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
